name: test
on:
  workflow_dispatch:
permissions: write-all
jobs:
  main:
    runs-on: ubuntu-latest
    #env:
      #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai' 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 安装支持
        run: pip install -r ./requirements.txt
      - name: 执行任务 -1.main.py
        run: |
          python main.py
      - name: Commit
        id: commit
        continue-on-error: true
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add ./
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S') mailCloud update done"
          git pull --rebase
      - uses: ad-m/github-push-action@master
        if: ${{ steps.commit.outcome == 'success' }}
